from dataclasses import dataclass


@dataclass
class ResearchReport:
    """
    Final report generated by ResearchMind.
    """

    topic: str = ""

    executive_summary: str = ""

    top_papers: str = ""

    paper_summaries: str = ""

    literature_review: str = ""

    knowledge_graph_summary: str = ""

    research_gaps: str = ""

    contradictions: str = ""

    research_ideas: str = ""

    research_proposal: str = ""

    conclusion: str = ""